### ISSUE TITLE
Stats API returns different value

### ISSUE THREAD

**Issue by zyi103** [figshare/user_documentation#137]
Hi, I have been using the Figshare stats API and found out there is a difference in the return value between
> https://stats.figshare.com/timeline/total/downloads/article/
> https://stats.figshare.com/total/downloads/article/

Is this intended? what's the difference?

Thanks,
![image](https://user-images.githubusercontent.com/25201475/124669007-ac6d7700-de7f-11eb-9342-049efc1baa5e.png)

**Comment by adrianp** [comment]
Hi @zyi103,

The timeline resource uses for filtering two query parameters, `start_date` and `end_date`; if these are not specified the result will reflect data for the past month. This is mentioned in the documentation at https://docs.figshare.com/#stats_timeline.

Let me know if I can provide further explanations!

**Comment by zyi103** [comment]
I missed this part in the document, thanks for the reply
