### ISSUE TITLE
How do I go about downloading a file?

### ISSUE THREAD

**Issue by danielduduta** [figshare/user_documentation#26]
Docs don't mention how do I go about downloading a file - public or private

**Comment by TomBaxter** [comment]
1(public): https://docs.figshare.com/api/articles/#read-public-article
1(private): https://docs.figshare.com/api/articles/#read-own-article

2: https://docs.figshare.com/api/presenters/file/#publicfilepresenter

3(public): https://docs.figshare.com/api/articles/#download-public-files
3(private): https://docs.figshare.com/api/articles/#download-private-files
