### ISSUE TITLE
[figshare web GUI]: hyphens removed from file names during download

### ISSUE THREAD

**Issue by dhimmel** [figshare/user_documentation#49]
_Note: this is not an API related bug, but I'm reporting this issue here for lack of a better place. Ideally, figshare could open a repository for bug reporting and feature requests, since email and Twitter don't cut it._

***

I've come across a bug [affecting our article](https://doi.org/10.6084/m9.figshare.3487685.v5). There are two files with hyphens in their names: `mutation-matrix.tsv.bz2` and `expression-matrix.tsv.bz2`. An [API call](https://api.figshare.com/v2/articles/3487685/versions/5) confirms the hyphens in the file names.

However, when you download `mutation-matrix.tsv.bz2` or `expression-matrix.tsv.bz2` from the web interface, the hyphen is stripped, i.e. `mutationmatrix.tsv.bz2` and `expressionmatrix.tsv.bz2`.

**Comment by adrianp** [comment]
Hi Daniel,

Stripping the hyphens is not accidental, the system was devised in this manner. Is this causing any issues for you?

Regarding the medium for reporting this kind of problems, we have a support portal available at https://support.figshare.com/.


Best,

Tudor

**Comment by dhimmel** [comment]
Thanks @adrianp for your help!

> Stripping the hyphens is not accidental, the system was devised in this manner. Is this causing any issues for you?

Yeah it's corrupting file names and causing confusion because the unaltered name is used everywhere else. It's especially odd because `-` is not a [dangerous character](http://superuser.com/a/358861 "What characters are safe in cross-platform file names for Linux, Windows and OS-X") for filenames. I would have at least expected a big warning when uploading the file whose name contains an unsupported character.

> Regarding the medium for reporting this kind of problems, we have a support portal available at https://support.figshare.com/.

Thanks I created an account. It just was unclear to me whether my support ticket would be public. I try only to invest time into product feedback and bug reporting when that feedback will be public.

**Comment by adrianp** [comment]
The rules were devised a long time ago and were implemented in order to support our wide array of storage options. As I agree with you that in this particular case the hyphen should not cause any issues, we will look into removing this restriction, but cannot give an estimation on when this issue will be fixed.

As for the support portal, we also have a public side at https://support.figshare.com/discussions which is visible to all users.
