### ISSUE TITLE
Is there a way to associate exisiting articles with a project?

### ISSUE THREAD

**Issue by felliott** [figshare/user_documentation#55]
The Figshare web interface provides a method to associate pre-existing articles with projects, but I can't find any way to do that through the API.  Is that something that the API supports?  If not, it would be helpful to mention that in the article and project docs.  I'm happy to submit a patch if that's the case.  Thank you!

Cheers,
@felliott

**Comment by adrian-castravete** [comment]
The feature is not currently supported **API** wise, but will be in the near future. As for submitting a patch, please do if you like to :smile:.
