### ISSUE TITLE
Repository / documentation license?

### ISSUE THREAD

**Issue by dhimmel** [figshare/user_documentation#61]
Greetings, I didn't see a license for the content of this repository.

I'm one of the leaders of Project Cognoma -- an open source meetup group in Philly that's building a cancer research website. We host our data on figshare at https://doi.org/10.6084/m9.figshare.3487685.

We're building a [python package](https://github.com/cognoma/figshare) to automate our interactions with figshare. In https://github.com/cognoma/figshare/pull/2, @vasudevanv has included some code from the [API Docs](https://docs.figshare.com/api/).

The `cognoma/figshare` repo is BSD 3-Clause licensed. Is it cool for us to include any code from the API Docs in our package?

Finally, it would make reuse of the API Docs code easiest if you applied a license. For example, if you licensed all code snippets as CC0, the snippets would be compatible in all codebases.

**Comment by eduardgab** [comment]
Hi Daniel, 

Sure thing, you can use any code snippets from our Figshare Documentation. 
To remove any doubts regarding licensing terms, we've added a CC0 License file to the Repository. 

Let us know if there are any other questions. 

Cheers,
Eduard

**Comment by vasudevanv** [comment]
Great! Thanks a lot.

Best,
Vasu

**Comment by dhimmel** [comment]
Great confirming that https://github.com/figshare/user_documentation/commit/454b7c6313520cada6fdfe298d3f7211d01fef19 adds a CC0 1.0 License.

@eduardgab thanks a lot!
