### ISSUE TITLE
Unexpected response from API when sending invalid body

### ISSUE THREAD

**Issue by danielduduta** [figshare/user_documentation#9]
When creating a new collection, it doesn't specify which fields are mandatory.
I get {"message": "Bad data: The field is mandatory.", "code": "BadRequest"} but it doesn't say what field. 
Data used is collection_data = {'title': 'Sample demo collection', 
                   'description': 'sample demo desc'}
Data was not json encoded in the body, this means we have a logic error while loading the request.body

@tachirei @birocorneliu

**Comment by tachirei** [comment]
A fix for this should be merged into master and deployed on stage.
When request.json_body is empty, NoParamsProvided exceptions will be raised.
When the json does not contain the 'title', a MissingParams('title') will be raised.
We'll test these changes soon.
